CmsClientApp/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CmsClientApp.Controllers
{
    public class DashboardController : Controller
    {
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Index()
        {
            ViewBag.username = HttpContext.Session.GetString("username");

            if (ViewBag.username != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }

        }

        public IActionResult AddDoctor()
        {

            return RedirectToAction("GetAllDoctors", "Doctor");

        }
        public IActionResult AddPatient()
        {

            return RedirectToAction("GetAllPatients", "Patient");

        }
        public IActionResult Schedule()
        {

            return RedirectToAction("ViewAppointments", "Appointment");

        }

        public IActionResult Logout()
        {
            HttpContext.Session.SetString("username", "");
            HttpContext.Session.Clear();
            Response.Cookies.Delete("username");
            HttpContext.Response.Cookies.Delete("username");
            return RedirectToAction("Login", "Login");

        }
    }
}

CmsClientApp/Controllers/ScheduleAppointmentController.cs
using CmsClientApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using CmsAPI.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace CmsClient.Controllers
{
    public class ScheduleAppointmentController : Controller
    {
       
        string Baseurl = "https://cmsapi12.azurewebsites.net/";
        //Get all the Appointments
        public async Task<IActionResult> ViewAppointments()
        {
            List<Schedule> ScheduleInfo = new List<Schedule>();

            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync("api/Schedules");

                if (Res.IsSuccessStatusCode)
                {
                    var ScheduleResponse = Res.Content.ReadAsStringAsync().Result;
                    ScheduleInfo = JsonConvert.DeserializeObject<List<Schedule>>(ScheduleResponse);

                }
                return View(ScheduleInfo);
            }

        }
        //Booking an Appointment
        [HttpGet]
        public async Task<IActionResult> Create(string d)
        {
            List<Doctor> DoctorsList = new List<Doctor>();

            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync("api/Doctors");

                if (Res.IsSuccessStatusCode)
                {
                    var DoctorResponse = Res.Content.ReadAsStringAsync().Result;
                    DoctorsList = JsonConvert.DeserializeObject<List<Doctor>>(DoctorResponse);

                }
            }
            List<Patient> Patientslist = new List<Patient>();

            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync("api/Patients");

                if (Res.IsSuccessStatusCode)
                {
                    var PatientResponse = Res.Content.ReadAsStringAsync().Result;
                    Patientslist = JsonConvert.DeserializeObject<List<Patient>>(PatientResponse);

                }
            }
            //Getting a patientID from the database
            var patientid = (from p in Patientslist
                             select p.PatientId).ToList();
            ViewBag.pid = new SelectList(patientid);

            //Storing the specialization in a ViewBag
            ViewBag.specialization = d;

            //Populating doctor Names using specialization from the database
            var doctorsobj = (from k in DoctorsList
                              where k.Specialization == d
                              select k.Firstname).ToList();
            ViewBag.doctor = new SelectList(doctorsobj);

            //Storing the available list of doctor details
            var availablelist = (from a in DoctorsList
                                 where a.Specialization == d
                                 select a);
            ViewBag.availablelist = availablelist;



            return View();

        }

        [HttpPost]
        public async Task<IActionResult> Create(Schedule s)
        {
            Schedule sobj = new Schedule();

            //  HttpClient obj = new HttpClient();
            using (var httpClient = new HttpClient())
            {
                httpClient.BaseAddress = new Uri(Baseurl);
                StringContent content = new StringContent(JsonConvert.SerializeObject(s), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync("api/Schedules", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    sobj = JsonConvert.DeserializeObject<Schedule>(apiResponse);
                }
            }

           
            return RedirectToAction("ViewAppointments");
        }

        public async Task<IActionResult> Timeslot(string Doctorname, string VisitDate)
        {
            DateTime visitdate = DateTime.Parse(VisitDate);

            int id = 0;
            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync("api/Doctors/DoctorIDByDoctorName/" + Doctorname);

                if (Res.IsSuccessStatusCode)
                {
                    var DoctorResponse = Res.Content.ReadAsStringAsync().Result;
                    id = JsonConvert.DeserializeObject<int>(DoctorResponse);

                }

            }
            //List of Doctor-Visiting Hours 
            List<int> Doctoravailability = new List<int>();
            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync("api/Doctors/VisitinghourList/" + id);

                if (Res.IsSuccessStatusCode)
                {
                    var DoctorResponse = Res.Content.ReadAsStringAsync().Result;
                    Doctoravailability = JsonConvert.DeserializeObject<List<int>>(DoctorResponse);

                }

            }
            //List of Booked Appointment Time
            List<int> Appointment = new List<int>();
            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync("api/Doctors/BookedAppointment/" + Doctorname + "/" + VisitDate);
                if (Res.IsSuccessStatusCode)
                {
                    var ScheduleResponse = Res.Content.ReadAsStringAsync().Result;
                    Appointment = JsonConvert.DeserializeObject<List<int>>(ScheduleResponse);

                }

            }
            //List of Available slots=[Doctoravailability - Appointment]
            List<int> AvailableSlots = new List<int>();
            int starttime = Doctoravailability[0];
            int endtime = Doctoravailability[1];
            for (int currenttime = starttime; currenttime <= endtime; currenttime++)
            {

                bool allow = true; //initially set true

                foreach (int appointmenttime in Appointment)
                {
                    if (currenttime == appointmenttime)
                    {
                        allow = false;//slots are not available
                        break;
                    }
                }
                if (allow == true)//slots are available
                {
                    AvailableSlots.Add(currenttime);
                }

            }
            ViewBag.res = AvailableSlots;
            return PartialView("Timeslot");
        }

        //Cancel an Appointment
        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            TempData["AppointmentId"] = id;
            Schedule s = new Schedule();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://cmsapi12.azurewebsites.net/api/Schedules/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    s = JsonConvert.DeserializeObject<Schedule>(apiResponse);
                }
            }
            return View(s);

        }

        [HttpPost]
        public async Task<ActionResult> Delete(Schedule s)
        {
            int appid = Convert.ToInt32(TempData["AppointmentId"]);
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync("https://cmsapi12.azurewebsites.net/api/Schedules/" + appid))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            
            return RedirectToAction("ViewAppointments");
        }
    }
}

CmsClientApp/Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{ }

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/css/style.css" rel="stylesheet" />
    <style>
        .navigation li {
            display: inline-block;
        }
    </style>
    <style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.sidenav .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 36px;
  margin-left: 50px;
}

#main {
  transition: margin-left .5s;
  padding: 16px;
}

    </style>
</head>
<body>

    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a class="nav-link btn btn-outline-success" asp-area="" asp-controller="Doctor" asp-action="GetAllDoctor">Doctors</a>        
        <a class="nav-link btn btn-outline-success" asp-area="" asp-controller="Patient" asp-action="GetAllPatients">Patients</a>                
        <a class="nav-link btn btn-outline-success" asp-area="" asp-controller="ScheduleAppointment" asp-action="ViewAppointments">Appointments</a>
        <a class="nav-link btn btn-outline-success" asp-area="" asp-controller="Dashboard" asp-action="Logout">Logout</a>
       
    </div>

    <div id="main">
        @*<h2>Sidenav Push Example</h2>
        <p>Click on the element below to open the side navigation menu, and push this content to the right.</p>*@
        <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Dashboard</span>

        <div class="main">
            <h2>Welcome <i>@ViewBag.username !</i></h2>
        </div>
    </div>

    <script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
    </script>

</body>

<!--<header>
    <link href="~/css/style.css" rel="stylesheet" />
    <style>
        .navigation li {
            display: inline-block;
        }
    </style>-->
    <!-- Image and text -->
    <!--<nav class="navbar navbar-light bg-light">
    <nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">
            <img src="~/images/Stone-Clinic-Logo.png" width="50" height="50">
            The Stone Clinic
        </a>
    </nav>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse justify-content-end">
            <ul class="navigation">
                <li class="nav-item">
                    <a class="nav-link btn btn-outline-success" asp-area="" asp-controller="Doctor" asp-action="GetAllDoctor">Add Doctor</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-outline-success" asp-area="" asp-controller="Patient" asp-action="GetAllPatients">Add Patient</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-outline-success" asp-area="" asp-controller="ScheduleAppointment" asp-action="ViewAppointments">Schedule Appointment</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-outline-success" asp-area="" asp-controller="Login" asp-action="Login">Logout</a>
                </li>
            </ul>
        </div>
    </nav>

</header>-->