CmsClientApp/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CmsClientApp.Models
{
    public class Login
    {
        [Key]
        [Required(ErrorMessage = "Username is Required")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Password is Required")]
        public string Password { get; set; }

        public string ErrorMessage { get; set; }
    }
}

CmsClientApp/Controllers/LoginController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using CmsClientApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using CmsClientApp.Helper;

namespace CmsClientApp.Controllers
{
    public class LoginController : Controller
    {
        private readonly CmsAPI.Data.CmsContext _db;
        
        public LoginController(CmsAPI.Data.CmsContext db)
        {
            _db = db;
           
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        
        [HttpPost]
        public IActionResult Login(Login l)
        {
            var PasswordHash= EncodePassword.GetMd5Hash(l.Password);
            CmsAPI.Model.UserSetup obj = (from i in _db.UserSetup
                                          where i.Username == l.Username && i.Password == PasswordHash/*l.Password*/
                                          select i).FirstOrDefault();

            if (obj != null)
            {
                if (obj.Password != l.Password)
                {
                    ModelState.AddModelError(nameof(l.ErrorMessage), "Incorrect Password");
                    return View();
                }
                string username = obj.Username;
                HttpContext.Session.SetString("username", username);
                return RedirectToAction("Index", "Dashboard");
            }
            else
            {
                ModelState.AddModelError(nameof(l.ErrorMessage), "Incorrect Username");
                //ViewBag.errormsg = "Incorrect Username or Password";
                return View();
            }

        }

        
    }
}

CmsClientApp/Controllers/UserSetupController.cs
using CmsClientApp.Models;
using CmsClientApp.Helper;
using CmsClientApp.ViewRegModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Configuration;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace CmsClientApp.Controllers
{
    public class UserSetupController : Controller
    {
        private IConfiguration _configuration;
       
        public UserSetupController(IConfiguration configuration)
        {          
            _configuration = configuration;
        }
        string Baseurl = "https://cmsapi12.azurewebsites.net/";
        public async Task<IActionResult> GetAllUsers()
        {
            List<UserRegistration> UserSetupInfo = new List<UserRegistration>();

            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync("api/UserSetups");

                if (Res.IsSuccessStatusCode)
                {
                    var UserSetupResponse = Res.Content.ReadAsStringAsync().Result;
                    UserSetupInfo = JsonConvert.DeserializeObject<List<UserRegistration>>(UserSetupResponse);

                }
                return View(UserSetupInfo);
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            Random rnd = new Random();
            ViewBag.captcha1 = rnd.Next(0, 20);// returns random integers
            ViewBag.captcha2 = rnd.Next(10, 20);
            ViewBag.resultCaptcha = ViewBag.captcha1 + ViewBag.captcha2;
            return View("RegisterForm");
        }
        [HttpPost]
        public async Task<IActionResult> Create(RegisterForm reg)
        {
            MainHelper main = new MainHelper(_configuration);
            //var EncodePassword= GetMd5Hash(reg.Password);
            //reg.Password=EncodePassword;
            UserRegistration Uobj = new UserRegistration();
            //Assign the value for this fields
            Uobj.Username = reg.Username;
            Uobj.Firstname = reg.Firstname;
            Uobj.Lastname = reg.Lastname;
            Uobj.EmailId = reg.Email;
            Uobj.Password = reg.Password;
            Uobj.ConfirmPassword = reg.ConfirmPassword;
            Uobj.SecurityQuestion = reg.SecurityQuestion;
            Uobj.Answer = reg.Answer;
            Uobj.Status = false;
            Uobj.CreationDate = DateTime.Now;
            Uobj.SecurityCode = Helper.RandomHelper.RandomString(6);



            using (var httpClient = new HttpClient())
            {
                httpClient.BaseAddress = new Uri("https://cmsapi12.azurewebsites.net/");
                StringContent content = new StringContent(JsonConvert.SerializeObject(Uobj), Encoding.UTF8, "application/json");
                if (reg.Captcha == reg.resultCaptcha)
                {
                    using (var response = await httpClient.PostAsync("api/UserSetups", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                       
                        if (response.IsSuccessStatusCode)
                        {
                            //string apiResponse = await response.Content.ReadAsStringAsync();
                            //string result = JsonConvert.DeserializeObject<string>(apiResponse);
                            try
                            {

                                //sending email to user
                                string body = "<!DOCTYPE html>" +
                                                "<html> " +
                                                    "<body style=\"background -color:#ff7f26;text-align:center;\"> " +
                                                    "<h3 style=\"color:#051a80;\">Welcome </h3> " + Uobj.Username +
                                                    "<h3>Thankyou for registration!</h3>" +
                                                    "<h3>Security Code: </h3>" + Uobj.SecurityCode +
                                                    "<h4>Please click on the following link to verify your account.</h4> " +
                                                    "<a href='https://cms12.azurewebsites.net/UserSetup/Activate'>Verify</a>" +
                                                    "</body> " +
                                                "</html>";
                                                
                                
                                main.Send(_configuration["Gmail:Username"], Uobj.EmailId, "Successfully Registered!", body);                                
                                HttpContext.Session.SetString("username", Uobj.Username);
                                HttpContext.Session.SetString("purpose", "login");                              
                                return View("AccountActivate");


                            }
                            catch
                            {
                                
                                Random rnd = new Random();
                                ViewBag.captcha1 = rnd.Next(0, 20);// returns random integers >= 10 and < 19
                                ViewBag.captcha2 = rnd.Next(10, 20);
                                ViewBag.resultCaptcha = ViewBag.captcha1 + ViewBag.captcha2;
                                reg.Email = "";
                                return View("RegisterForm", reg);
                            }

                        }
                        else
                        {
                            
                            Random rnd = new Random();
                            ViewBag.captcha1 = rnd.Next(0, 20);// returns random integers >= 10 and < 19
                            ViewBag.captcha2 = rnd.Next(10, 20);
                            ViewBag.resultCaptcha = ViewBag.captcha1 + ViewBag.captcha2;

                            reg.Username = null;
                            reg.Captcha = null;
                            return View("RegisterForm", reg);
                        }

                    }
                }
                else
                {
                    Random rnd = new Random();
                    ViewBag.captcha1 = rnd.Next(0, 20);// returns random integers >= 10 and < 19
                    ViewBag.captcha2 = rnd.Next(10, 20);
                    ViewBag.resultCaptcha = ViewBag.captcha1 + ViewBag.captcha2;
                    ViewBag.captchaError = "Invalid Captcha";
                    return View("RegisterForm", reg);
                }
            }
        }
        [HttpGet]
        public IActionResult Activate()
        {

            //ViewBag.username = HttpContext.Session.GetString("username");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Activate(string securitycode)
        {
            List<UserRegistration> UserSetupInfo = new List<UserRegistration>();

            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync("api/UserSetups");

                if (Res.IsSuccessStatusCode)
                {
                    var UserSetupResponse = Res.Content.ReadAsStringAsync().Result;
                    UserSetupInfo = JsonConvert.DeserializeObject<List<UserRegistration>>(UserSetupResponse);

                }
            }
            UserRegistration obj = null;


            foreach (var i in UserSetupInfo)
            {

                if (i.SecurityCode == securitycode)
                {
                    int seconds = DateTime.Now.Subtract(i.CreationDate).Seconds;
                    if (seconds < 60)
                    {
                        obj = i;
                    }


                }
            }
            if (obj != null)
            {

                if (HttpContext.Session.GetString("purpose") == "login")
                {
                    obj.Status = true;
                    using (var httpClient = new HttpClient())
                    {
                        string username = obj.Username;
                        StringContent content1 = new StringContent(JsonConvert.SerializeObject(obj), Encoding.UTF8, "application/json");
                        using (var response = await httpClient.PutAsync("https://cmsapi12.azurewebsites.net/api/UserSetups/" + username, content1))
                        {
                            if (response.IsSuccessStatusCode)
                            {
                                try
                                {
                                    string body = "Dear " + obj.Username + "\nYour account is activated!\nNow you can use your user credentials to log in to your account";
                                    MainHelper main = new MainHelper(_configuration);
                                    main.Send(_configuration["Gmail:username"], obj.EmailId, "Verification Process Done!", body);
                                   
                                    return RedirectToAction("Login", "Login");
                                }
                                catch
                                {
                                    
                                    return View();

CmsClientApp/Views/Login/Login.cshtml
@model CmsClientApp.Models.Login

@{
    ViewData["Title"] = "Login";
}

<head>
    <meta charset="utf-8">
    <title>Signin Form</title>

    <link href="~/css/style.css" rel="stylesheet" />
</head>
<style>
    .navigation li {
        display: inline-block;
    }
    /* Center the image and position the close button */
    .imgcontainer {
        text-align: center;
        margin: 24px 0 12px 0;
        position: relative;
    }

    img.avatar {
        width: 20%;
        border-radius: 50%;
    }

</style>


<html lang="en" dir="ltr">

<body>
    <nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-dark">
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="navbar-brand" href="#">
                        <img src="~/images/Stone-Clinic-Logo.png" width="50" height="50">
                        The Stone Clinic
                    </a>
                </li>
            </ul>
        </div>
        <div class="navbar-collapse collapse justify-content-end">
            <ul class="navigation">
                <li class="nav-item">
                    <a class="nav-link btn btn-outline-success" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="center">
        <div class="imgcontainer">
            <img src="~/images/Stone-Clinic-Logo.png" alt="Avatar" class="avatar">
        </div>
        <h1>Signin</h1>
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>:
                <input asp-for="Username" class="form-control" placeholder="Username" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>:
                <input type="password" asp-for="Password" class="form-control" placeholder="Password" value="" id="myInput" />
                <input type="checkbox" onclick="myFunction()"> Show Password
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="pass">
                <a asp-area="" asp-controller="UserSetup" asp-action="ForgotPassword">Forgot Password?</a>
            </div>

            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>

            <div class="signup_link">
                Not a member? <a asp-area="" asp-controller="UserSetup" asp-action="Create">Signup</a>
            </div>
            <script>
                function myFunction() {
                    var x = document.getElementById("myInput");
                    if (x.type === "password") {
                        x.type = "text";
                    } else {
                        x.type = "password";
                    }
                }
            </script>

            @*for popup message*@
            @if (@ViewBag.errormsg != null)
            {
                <script type="text/javascript">

                  window.onload = function ()
                  {
                   alert("@ViewBag.errormsg");
                  };
                </script>
            }
        </form>
    </div>

</body>
</html>

@*<div>
        <a asp-action="Index">Back to List</a>
    </div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}